# Copyright 2020 Khushraj Rathod
#
# This file is part of TeleDrive.
#
# TeleDrive is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# TeleDrive is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with TeleDrive.  If not, see <https://www.gnu.org/licenses/>.

language: node_js
dist: bionic

node_js:
  - node

os:
  - osx
  - linux

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then unset CSC_KEY_PASSWORD CSC_LINK; fi

script:
  - |
    if [ -n "$TRAVIS_TAG" ]; then
        if [ "$TRAVIS_OS_NAME" = "linux" ]; then
            echo $SNAP_TOKEN | snapcraft login --with -
        fi
        yarn dist
    elif [ "$TRAVIS_OS_NAME" == "linux" ]; then
        cd docs
        yarn
        yarn build
        cd ..
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        git fetch origin
        mv website ..
        git checkout vercel
        rm -rf ./*
        mv ../website/* .
        git add .
        git commit --amend --no-edit
        git remote set-url origin https://KhushrajRathod:$GITHUB_TOKEN@github.com/KhushrajRathod/TeleDrive.git
        git push -f
    fi

addons:
  apt:
    packages:
      - fakeroot
      - libc++1
  snaps:
    - name: snapcraft
      confinement: classic